# Generated by Django 4.2.3 on 2023-07-28 18:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Figure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("authors", models.CharField(max_length=200)),
                ("journal", models.CharField(max_length=200)),
                ("volume", models.CharField(max_length=200)),
                ("issue", models.CharField(max_length=200)),
                ("pages", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=200)),
                ("doi", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("authors", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                (
                    "pdf",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/media/papers"
                        ),
                        upload_to="pdfs/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("figures", models.ManyToManyField(to="pdfparser.figure")),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("authors", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                ("doi", models.CharField(max_length=200)),
                ("figures", models.ManyToManyField(to="pdfparser.figure")),
                ("references", models.ManyToManyField(to="pdfparser.reference")),
                ("sections", models.ManyToManyField(to="pdfparser.section")),
            ],
        ),
    ]
