# Generated by Django 4.2.3 on 2023-07-29 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pdfparser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uploadedpaper",
            name="pdf",
            field=models.FileField(upload_to="pdfs/", verbose_name="test.pdf"),
        ),
    ]
