# Generated by Django 4.2.3 on 2023-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdfparser", "0003_rename_id_paper_paper_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedPaper",
        ),
        migrations.AddField(
            model_name="paper",
            name="pdf",
            field=models.FileField(blank=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="abstract",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="authors",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="paper",
            name="doi",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="paper",
            name="figures",
            field=models.ManyToManyField(blank=True, to="pdfparser.figure"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="references",
            field=models.ManyToManyField(blank=True, to="pdfparser.reference"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="sections",
            field=models.ManyToManyField(blank=True, to="pdfparser.section"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
